In [1]:
# Importing all necessary libraries
import cv2
import os

# Read the video from specified path
cam = cv2.VideoCapture("/content/vid1.avi")

try:
	
	# creating a folder named data
	if not os.path.exists('data'):
		os.makedirs('data')

# if not created then raise error
except OSError:
	print ('Error: Creating directory of data')

# frame
currentframe = 0

while(True):
	
	# reading from frame
	ret,frame = cam.read()

	if ret:
		# if video is still left continue creating images
		name = './data/frame' + str(currentframe) + '.jpg'
		print ('Creating...' + name)

		# writing the extracted images
		cv2.imwrite(name, frame)

		# increasing counter so that it will
		# show how many frames are created
		currentframe += 1
	else:
		break

# Release all space and windows once done
cam.release()
cv2.destroyAllWindows()


Creating..../data/frame0.jpg
Creating..../data/frame1.jpg
Creating..../data/frame2.jpg
Creating..../data/frame3.jpg
Creating..../data/frame4.jpg
Creating..../data/frame5.jpg
Creating..../data/frame6.jpg
Creating..../data/frame7.jpg
Creating..../data/frame8.jpg
Creating..../data/frame9.jpg
Creating..../data/frame10.jpg
Creating..../data/frame11.jpg
Creating..../data/frame12.jpg
Creating..../data/frame13.jpg
Creating..../data/frame14.jpg
Creating..../data/frame15.jpg
Creating..../data/frame16.jpg
Creating..../data/frame17.jpg
Creating..../data/frame18.jpg
Creating..../data/frame19.jpg
Creating..../data/frame20.jpg
Creating..../data/frame21.jpg
Creating..../data/frame22.jpg
Creating..../data/frame23.jpg
Creating..../data/frame24.jpg
Creating..../data/frame25.jpg
Creating..../data/frame26.jpg
Creating..../data/frame27.jpg
Creating..../data/frame28.jpg
Creating..../data/frame29.jpg
Creating..../data/frame30.jpg
Creating..../data/frame31.jpg
Creating..../data/frame32.jpg
Creating..../data/fr

In [2]:
from os import listdir
from os.path import isfile, join
import numpy
import cv2
import natsort
from skimage.metrics import structural_similarity as ssim
mypath='/content/data'
onlyfiles = [ f for f in listdir(mypath) if isfile(join(mypath,f)) ]
onlyfiles=natsort.natsorted(onlyfiles)
images = numpy.empty(len(onlyfiles), dtype=object)
ssim_list=[]
for n in range(0, len(onlyfiles)):
  images[n] = cv2.imread( join(mypath,onlyfiles[n]) )
for n in range(0,len(images)-1):
  img1=images[n]
  img2=images[n+1]
  image1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
  image2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)          # trainImage
  score, diff = ssim(image1, image2, full=True)
  print("SSIM between frames: {} "+ str(n) + " and " + str(n+1)+" is "+ format(score))
  print(type(score))
  ssim_list.append(score)
  ssim_array=numpy.array(ssim_list)
 # ssim_tuple=tuple(ssim_list)
print(type(ssim_array))

SSIM between frames: {} 0 and 1 is 0.9870920709556791
<class 'numpy.float64'>
SSIM between frames: {} 1 and 2 is 0.9930326468255442
<class 'numpy.float64'>
SSIM between frames: {} 2 and 3 is 0.9982709467916623
<class 'numpy.float64'>
SSIM between frames: {} 3 and 4 is 0.9982131812894574
<class 'numpy.float64'>
SSIM between frames: {} 4 and 5 is 0.9989543282683113
<class 'numpy.float64'>
SSIM between frames: {} 5 and 6 is 0.9985736036662117
<class 'numpy.float64'>
SSIM between frames: {} 6 and 7 is 0.9986141020859772
<class 'numpy.float64'>
SSIM between frames: {} 7 and 8 is 0.9987427891813588
<class 'numpy.float64'>
SSIM between frames: {} 8 and 9 is 0.9990961148276998
<class 'numpy.float64'>
SSIM between frames: {} 9 and 10 is 0.9989117208104634
<class 'numpy.float64'>
SSIM between frames: {} 10 and 11 is 0.9985589306046849
<class 'numpy.float64'>
SSIM between frames: {} 11 and 12 is 0.9882343693180798
<class 'numpy.float64'>
SSIM between frames: {} 12 and 13 is 0.9670558601622918
<cl

In [3]:
!pip install moviepy
!pip install imageio==2.4.1

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.3/3.3 MB 25.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for imageio: filename=imageio-2.4.1-py3-none-any.whl size=3303886 sha256=8eaa24179a6d8969a162a0f6ccf68a4718160ede549cef3e337ecdc6faed4a2e
  Stored in directory: /root/.cache/pip/wheels/b7/44/b7/2e7cc9c5fe4a893b9cc83a010d4410557bedf6cf3b5829f497
Successfully built imageio
  Attempting uninstall: imageio
    Found existing installation: imageio 2.25.1
    Uninstalling imageio-2.25.1:
      Successfully uninstalled imageio-2.25.1


In [4]:
import sys
import numpy as np
import cv2
import moviepy.editor as mpy
from matplotlib import pyplot as plt

vid = mpy.VideoFileClip('/content/vid1.avi')
time_stamp=[]
average=[]
for i, (tstamp, frame) in enumerate(vid.iter_frames(with_times=True)):
  #print("Frame no: "+str(i)+" with time stamp "+str(round(tstamp%60,2)))
  time_stamp.insert(i,round(tstamp%60,2))
print(time_stamp)
print(len(time_stamp))
#duration of a single frame
duration=np.diff(time_stamp)
print(duration)
print(np.mean(duration))

Imageio: 'ffmpeg-linux64-v3.3.1' was not found on your computer; downloading it now.
Try 1. Download from https://github.com/imageio/imageio-binaries/raw/master/ffmpeg/ffmpeg-linux64-v3.3.1 (43.8 MB)
Downloading: 8192/45929032 bytes (0.0%)1318912/45929032 bytes (2.9%)4259840/45929032 bytes (9.3%)7897088/45929032 bytes (17.2%)11419648/45929032 bytes (24.9%)14671872/45929032 bytes (31.9%)18251776/45929032 bytes (39.7%)21848064/45929032 bytes (47.6%)25616384/45929032 bytes (55.8%)28876800/45929032 bytes (62.9%)32374784/45929032 bytes (70.5%)36077568/45929032 bytes (78.6%)39575552/45929032 bytes (86.2%)4

In [5]:
timestamp_quota=round(len(time_stamp)*np.mean(duration),0)
print(timestamp_quota)
timestamp_quota_int=timestamp_quota.astype(int)
print(timestamp_quota_int)

5.0
5


Following code denotes inserted frames

In [191]:
threshold=0.9 #threshold value has to be found out
i=0
for j in range(0,len(ssim_array)):
  if(ssim_array[j]<threshold):
    print(timestamp_quota_int,j,ssim_array[j])

  
  
 
  

0 18 0.193431275980246
0 23 0.192900823065573
0 52 0.23754568418616714
0 57 0.23732668537000157
0 81 0.11912335024687083
0 86 0.11962355463526096
0 93 0.11576403835021706
0 98 0.1160148086772125
0 103 0.28589605237653914
0 108 0.2842945276584038
0 109 0.23672075882750462
0 114 0.23675520765681174


Numpy implementation of sliding window . Reference https://numpy.org/devdocs/reference/generated/numpy.lib.stride_tricks.sliding_window_view.html#numpy.lib.stride_tricks.sliding_window_view

In [52]:
i=0
j=0
while(i<=128):
  while(j<5):
    if(i<j):
      print(i,j)
    j=j+1
  i=i+1

0 1
0 2
0 3
0 4


In [65]:
if(v[0][0]<0.9):
  print("hiiiii")
else:
  print("helllo")

helllo


In [73]:
# outer loop
for i in range(1, 11):
    # nested loop
    # to iterate from 1 to 10
    for j in range(1, 11):
        # print multiplication
        print(j)
    print()

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10

1
2
3
4
5
6
7
8
9
10



In [91]:
print(v[0:10])

[[0.98709207 0.99303265 0.99827095 0.99821318 0.99895433]
 [0.99303265 0.99827095 0.99821318 0.99895433 0.9985736 ]
 [0.99827095 0.99821318 0.99895433 0.9985736  0.9986141 ]
 [0.99821318 0.99895433 0.9985736  0.9986141  0.99874279]
 [0.99895433 0.9985736  0.9986141  0.99874279 0.99909611]
 [0.9985736  0.9986141  0.99874279 0.99909611 0.99891172]
 [0.9986141  0.99874279 0.99909611 0.99891172 0.99855893]
 [0.99874279 0.99909611 0.99891172 0.99855893 0.98823437]
 [0.99909611 0.99891172 0.99855893 0.98823437 0.96705586]
 [0.99891172 0.99855893 0.98823437 0.96705586 0.99632362]]


In [88]:
print("0,0",v[0][0])
print("0,1",v[0][1])
print("0,2",v[0][2])
print("0,3",v[0][3])
print("0,4",v[0][4])
print("1,0",v[1][0])
print("1,1",v[1][1])
print("1,2",v[1][2])
print("1,3",v[1][3])
print("1,4",v[1][4])

0,0 0.9870920709556791
0,1 0.9930326468255442
0,2 0.9982709467916623
0,3 0.9982131812894574
0,4 0.9989543282683113
1,0 0.9930326468255442
1,1 0.9982709467916623
1,2 0.9982131812894574
1,3 0.9989543282683113
1,4 0.9985736036662117


In [101]:
print(v[16][2])
print(v[17][1])
print(v[18][0])

0.193431275980246
0.193431275980246
0.193431275980246


In [102]:
v = numpy.lib.stride_tricks.sliding_window_view(ssim_array, timestamp_quota_int)
print(len(v))
count=0
for i in range(0,124):
  for j in range(0,5):
    if(v[i][j]<0.9):
      print(i,j,v[i][j])
      count=count+1
print(count)


124
14 4 0.193431275980246
15 3 0.193431275980246
16 2 0.193431275980246
17 1 0.193431275980246
18 0 0.193431275980246
19 4 0.192900823065573
20 3 0.192900823065573
21 2 0.192900823065573
22 1 0.192900823065573
23 0 0.192900823065573
48 4 0.23754568418616714
49 3 0.23754568418616714
50 2 0.23754568418616714
51 1 0.23754568418616714
52 0 0.23754568418616714
53 4 0.23732668537000157
54 3 0.23732668537000157
55 2 0.23732668537000157
56 1 0.23732668537000157
57 0 0.23732668537000157
77 4 0.11912335024687083
78 3 0.11912335024687083
79 2 0.11912335024687083
80 1 0.11912335024687083
81 0 0.11912335024687083
82 4 0.11962355463526096
83 3 0.11962355463526096
84 2 0.11962355463526096
85 1 0.11962355463526096
86 0 0.11962355463526096
89 4 0.11576403835021706
90 3 0.11576403835021706
91 2 0.11576403835021706
92 1 0.11576403835021706
93 0 0.11576403835021706
94 4 0.1160148086772125
95 3 0.1160148086772125
96 2 0.1160148086772125
97 1 0.1160148086772125
98 0 0.1160148086772125
99 4 0.28589605237653

In [15]:
threshold=0.9
v = numpy.lib.stride_tricks.sliding_window_view(ssim_array, timestamp_quota_int)
count=0
for i in range (0,len(v)):
  for j in range(0,timestamp_quota_int):
    if(v[i][j]<threshold):
      print(v[i][j])
      count=count+1
print(count)


0.193431275980246
0.193431275980246
0.193431275980246
0.193431275980246
0.193431275980246
0.192900823065573
0.192900823065573
0.192900823065573
0.192900823065573
0.192900823065573
0.23754568418616714
0.23754568418616714
0.23754568418616714
0.23754568418616714
0.23754568418616714
0.23732668537000157
0.23732668537000157
0.23732668537000157
0.23732668537000157
0.23732668537000157
0.11912335024687083
0.11912335024687083
0.11912335024687083
0.11912335024687083
0.11912335024687083
0.11962355463526096
0.11962355463526096
0.11962355463526096
0.11962355463526096
0.11962355463526096
0.11576403835021706
0.11576403835021706
0.11576403835021706
0.11576403835021706
0.11576403835021706
0.1160148086772125
0.1160148086772125
0.1160148086772125
0.1160148086772125
0.1160148086772125
0.28589605237653914
0.28589605237653914
0.28589605237653914
0.28589605237653914
0.28589605237653914
0.2842945276584038
0.2842945276584038
0.23672075882750462
0.2842945276584038
0.23672075882750462
0.2842945276584038
0.2367207

In [190]:
for i in range(0,5):
  if(ssim_array[i]<threshold):
    print(timestamp_quota_int,i,ssim_array[i])
  timestamp_quota_int=5+timestamp_quota_int

  timestamp_quota_int=timestamp_quota_int+timestamp_quota_int



41943040 18 0.193431275980246
1342177280 23 0.192900823065573
720575940379279360 52 0.23754568418616714
4611686018427387904 57 0.23732668537000157
0 81 0.11912335024687083
0 86 0.11962355463526096
0 93 0.11576403835021706
0 98 0.1160148086772125
0 103 0.28589605237653914
0 108 0.2842945276584038
0 109 0.23672075882750462
0 114 0.23675520765681174


IndexError: ignored